### ISSUE TITLE
Cannot run cnd (pycparser version issue?)

### ISSUE THREAD

**Issue by anntzer** [inducer/cnd#2]
```
$ cnd -E --cpp='cpp -std=c99' ~/src/cnd/examples/basic.c
ERROR: /usr/lib/python3.4/site-packages/pycparser/c_parser.py:1170: Symbol 'initializer_list_opt' used, but not defined as a token or a rule
Traceback (most recent call last):
  File "/home/antony/src/cnd/bin/cnd", line 25, in <module>
    cnd.run_standalone()
  File "/home/antony/src/cnd/cnd/__init__.py", line 689, in run_standalone
    parser = GnuCndParser()
  File "/home/antony/src/cnd/pycparserext-shipped/pycparserext/ext_c_parser.py", line 48, in __init__
    debug=yacc_debug, write_tables=False)
  File "/usr/lib/python3.4/site-packages/pycparser/ply/yacc.py", line 3214, in yacc
    raise YaccError("Unable to build parser")
pycparser.ply.yacc.YaccError: Unable to build parser
```

The system-wide pycparser is at v. 2.13 (and gets selected because you append the `*-shipped` versions to `sys.path` but I guess it'd be the same regardless?).

**Comment by inducer** [comment]
Thanks for the report!

**Comment by anntzer** [comment]
There is no commit `f8491b08aa5d5f624628ba6c010327722941c7b6` in the pycparserext repo right now (i.e. `git submodule update` fails even after running git pull on pycparserext-shipped)

**Comment by inducer** [comment]
Oops. Forgot to push. Now fixed, thanks for your patience.

**Comment by anntzer** [comment]
Still not there:

```
(git) python2 ../bin/cnd -E --cpp='cpp -std=c99' ~/src/cnd/examples/basic.c
WARNING: ../pycparser-shipped/pycparser/plyparser.py:42: Rule 'initializer_list_opt' defined, but not used
WARNING: There is 1 unused rule
WARNING: Symbol 'initializer_list_opt' is unreachable
Traceback (most recent call last):
  File "../bin/cnd", line 25, in <module>
    cnd.run_standalone()
  File "../cnd/__init__.py", line 690, in run_standalone
    ast = parser.parse(src, filename=in_file)
  File "../pycparserext-shipped/pycparserext/ext_c_parser.py", line 64, in parse
    return self.cparser.parse(text, lexer=self.clex, debug=debuglevel)
  File "../pycparser-shipped/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "../pycparser-shipped/pycparser/ply/yacc.py", line 971, in parseopt_notrack
    p.callable(pslice)
  File "../pycparserext-shipped/pycparserext/ext_c_parser.py", line 244, in p_declarator_1
    % type(p[1]))
NotImplementedError: cannot attach attributes to nodes of type '<class 'pycparser.c_ast.FuncDecl'>'
```

**Comment by inducer** [comment]
Works for me as of f37a3509c5e.
